### ISSUE TITLE
Consider moving `mongodb/mongodb` from required to suggested extensions

### ISSUE THREAD

**Issue by fangel** [imbo/imbo#523] opened 2017-01-26 11:35 UTC
Right now, the [package.json](https://github.com/imbo/imbo/blob/develop/composer.json#L31) lists `mongodb/mongodb` as a required dependency.

Personally, I think that is rather confusing, especially since Imbo doesn't require the use of the Mongo db- or storage-adapters, and will happily work with Doctrine/Filesystem.
Secondly it also makes it unnecessary to list `ext-mongodb` as a suggested dependency, because it's already a required dependency of `mongodb/mongodo`, so transitively `ext-mongodb` is actually required by Imbo.

I would suggest moving `mongodb/mongodb` to suggested and/or dev-dependencies, because depending on configuration it might not actually be required.

Right now, I install Imbo using `composer install --ignore-platform-reqs` because I would rather not install `ext-mongodb` when I do not actually need it for anything.

---

The same logic actually also applies to `aws/aws-sdk-php` since it's only required if you use the S3-storage adapter, so it should maybe only be a suggested dependency. It is, however, not nearly as annoying because it doesn't rely on a extension.

Kind regards
Morten

**Comment by matslindh** [comment] 2017-01-26 12:08
The mondodb dependency has been .. on and off. It was previously in require, then it was in require-dev, but [was moved back to require again](https://github.com/imbo/imbo/pull/471).

I'd support moving it back to suggests and require-dev for Imbo3 (which [was also mentioned the last time the DBAL was discussed](https://github.com/imbo/imbo/issues/472#issuecomment-218113386)).

`aws/aws-sdk-php` is currently in suggest as well, so I'm not sure why we still have it in require. @christeredvartsen ?

**Comment by christeredvartsen** [comment] 2017-01-26 12:26
bcca882cf00683db7f6fc9140ccd4b5b562426f9 seems to be the commit that put it in there, but I can't remember the reason. The commit message alone has some "reason", but can't remember what really triggered the change. I agree that both this and the mongo dependency should be put in `require-dev` and `suggest`.

**Comment by matslindh** [comment] 2017-01-26 12:48
My guess is that it's caused by `aws-sdk-php` introducing multiple non-backwards-compatible changes around that time, but these should be fixed after #495 was merged.

**Comment by matslindh** [comment] 2017-01-26 13:48
I've created a PR that does the changes discussed. See if it's more suitable.

I've kept the DBAL dependency for now as it doesn't depend on any extensions that have to be compiled.

**Comment by christeredvartsen** [comment] 2017-05-28 17:16
This has been resolved in one of the many PRs merged as of late.

**Closed by christeredvartsen** 2017-05-28 17:16 UTC
